---
substitutions:
  name: "econet-hvac"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  external_components_source: github://esphome-econet/esphome-econet@main
  logger_level: WARN
  econet_update_interval: 30s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: "2023.2.0"
  platform: $platform
  board: $board
  project:
    name: "esphome-econet.esphome-econet"
    version: 0.3.0

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_hvac.yaml@main
  import_full_config: false

preferences:
  flash_write_interval: "24h"

wifi:
  ap:

captive_portal:

api:

ota:

logger:
  baud_rate: 0  # Make sure logging is not using the serial port
  level: ${logger_level}
  tx_buffer_size: 2000

external_components:
  - source: ${external_components_source}

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

econet:
  uart_id: uart_0
  model: "HVAC"
  update_interval: ${econet_update_interval}
  on_datapoint_update:
    - sensor_datapoint: AIRHSTAT
      datapoint_type: raw
      then:
        # yamllint disable rule:line-length
        - lambda: |-
            ESP_LOGD("main", "on_datapoint_update %s", format_hex_pretty(x).c_str());
            id(blower_cfm).publish_state((x[16] << 8) + x[17]);
            id(blower_rpm).publish_state((x[20] << 8) + x[21]);
        # yamllint enable rule:line-length

climate:
  - platform: econet
    name: "HVAC"
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f

sensor:
  - platform: econet
    name: "HVAC Operating Mode"
    sensor_datapoint: HVACMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
    icon: "mdi:hvac"
  - platform: econet
    name: "HVAC Thermostat Temperature"
    sensor_datapoint: SPT_STAT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Cooling Setpoint"
    sensor_datapoint: COOLSETP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Auto Mode"
    sensor_datapoint: AUTOMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
    icon: "mdi:hvac"
  - platform: econet
    name: "Thermostat Current Humidity"
    sensor_datapoint: RELH7005
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: "humidity"
    state_class: "measurement"
  - platform: econet
    name: "HVAC ODU Outside Air Temperature "
    sensor_datapoint: TEMP_OAT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Evaporator Temperature "
    sensor_datapoint: TEMP_EVP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Inverter Crank Speed"
    sensor_datapoint: ISCSPEED
    unit_of_measurement: ""
    accuracy_decimals: 1
    entity_category: "diagnostic"
    icon: "mdi:speedometer"
  - platform: econet
    name: "HVAC ODU Crankcase Heater Temperature"
    sensor_datapoint: TEMP_CPT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Expansion Valve Current Position"
    sensor_datapoint: EXACTUAL
    unit_of_measurement: ""
    accuracy_decimals: 1
    entity_category: "diagnostic"
    icon: "mdi:valve"
  - platform: econet
    name: "HVAC ODU Expansion Valve Super Heat"
    sensor_datapoint: EXVSUPER
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Suction Line Temp"
    sensor_datapoint: TEMP_OST
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Pressure Suction"
    sensor_datapoint: PRES_SUC
    unit_of_measurement: "PSI"
    accuracy_decimals: 1
    device_class: "pressure"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: template
    name: "HVAC Air Handler CFM"
    id: blower_cfm
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:fan"
  - platform: template
    name: "HVAC Air Handler RPM"
    id: blower_rpm
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:fan"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    entity_category: "diagnostic"

text_sensor:
  - platform: econet
    name: "HVAC Operating Mode Text"
    sensor_datapoint: HVACMODE
    icon: "mdi:hvac"
  - platform: econet
    name: "HVAC Auto Mode Text"
    sensor_datapoint: AUTOMODE
    icon: "mdi:hvac"

number:
  - platform: econet
    name: "HVAC Dehumidification Setting Control"
    number_datapoint: DHUMSETP
    min_value: 10
    max_value: 80
    step: 1
    mode: "slider"
    icon: "mdi:air-humidifier-off"

switch:
  - platform: econet
    name: "HVAC Dehumidification Enable State"
    switch_datapoint: DHUMENAB
    icon: "mdi:air-humidifier-off"
