---
sensor:
  - platform: econet
    src_address: ${primary_thermostat_address}
    id: zone${zonenumber}_cfm
    name: ${zonename} CFM
    sensor_datapoint: Z${zonenumber}CFMDSP
    request_mod: ${primary_thermostat_requestmod}
    state_class: "measurement"
    entity_category: "diagnostic"
    unit_of_measurement: "cfm"
