substitutions:
  name: econet
  device_description: "Communicate with Econet Netork"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "stockmopar.econet"
    version: 0.0.1

esp32:
  board: esp32dev
  framework: 
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:

logger:
  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)

external_components:
  - source: github://stockmopar/esphome-econet
#  - source: components

uart:
  id: uart_0
  baud_rate: 38400
  tx_pin: 
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

# The base UART communication hub.
econet:
  uart: uart_0
  model: "Tankless"

# Optional additional sensors.
sensor:
  - platform: econet
    temp_in:
      name: "Temperature In"
    temp_out:
      name: "Temperature Out"
    setpoint:
      name: "Set Point Temperature"
    btus_used:
      name: "BTUs Used"
    water_used:
      name: "Water Used"
    flow_rate:
      name: "Flow Rate"
    ignition_cycles:
      name: "Ignition Cycles"
    instant_btus:
      name: "Instant BTUs"

binary_sensor:
  - platform: econet
    enable_state:
      name: "Water Heater Enabled (Sensor)"

switch:
  - platform: econet
    name: "Water Heater Enabled"
    switch_datapoint: 0
    id: wh_enabled_switch