---
# packages:
#   econet: !include econet_hvac_furnace.yaml

text_sensor:
  - platform: econet
    name: z${zoneid}name
    sensor_datapoint: Z${zoneid}__NAME
    request_mod: ${requestmod}
    request_once: true

climate:
  - platform: econet
    id: econet_climate${zoneid}
    name: HVAC Zone ${zoneid}
    src_address: ${thermostat_address}
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STATNFAN
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"
    current_humidity_datapoint: RELH7005
    target_dehumidification_level_datapoint: DHUMSETP


sensor:
  - platform: econet
    name: Zone ${zoneid} CFM
    sensor_datapoint: Z${zoneid}CFMDSP
    request_mod: ${requestmod}
    accuracy_decimals: 1
    state_class: "measurement"
    entity_category: "diagnostic"
    unit_of_measurement: "cfm"
  - platform: econet
    name: Zone ${zoneid} humidity
    sensor_datapoint: ZON${zoneid}HUMD
    request_mod: ${requestmod}
    accuracy_decimals: 1
    state_class: "measurement"
    entity_category: "diagnostic"

binary_sensor:
  - platform: econet
    name: zone {zoneid} enabled
    sensor_datapoint: ZON${zoneid}ENAB
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
    disabled_by_default: true
    request_mod: ${requestmod}
    request_once: true
