substitutions:
  name_base:    Water Heater Garage # Base name for all entities created in HA from this configuration. This becomes "Friendly Name." 
                                    # Uppercase are converted to lowercase, spaces to underscore for entity ids. (Normal HA entity naming rules apply).
  name_esphome: water-heater-garage # Valid characters for esphome are: abcdefghijklmnopqrstuvwxyz0123456789-_ (lowercase, no spaces)
  ip_addr:      192.168.2.206       # Identify the IP Address after first installing the board via esphone. (See wifi: section below)
  ip_gateway:   192.168.2.1
  ip_subnet:    255.255.255.0
  device_description: "Communicate with Econet Netork"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name_esphome}
  comment: ${device_description}
  project:
    name: "stockmopar.econet"
    version: 0.0.2

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid:     !secret WIFI_SSID # wifi ssid
  password: !secret WIFI_PWD  # wifi password
  power_save_mode: none

# ~~~~~~~~~~~~~~~
# Consider enabling manual ip data here after the intial installation of the board onto the network.

# After initial installation, determine the assigned IP address for the board from the router, create a DHCP reservation for that address.

# Uncomment the manual_ip: section here and enter the data into the substitutions: section above, save and upload the configuration to ESPHome
#  manual_ip:
#    static_ip: ${ip_addr}
#    gateway:   ${ip_gateway}
#    subnet:    ${ip_subnet}
# ~~~~~~~~~~~~~~~

# Enable the Home assistant API
api:

# Enable OTA updating for changes to this configuration file
ota:

logger:
  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)
  level: INFO
  tx_buffer_size: 2000

external_components:
  - source: github://stockmopar/esphome-econet
#  - source: components


uart:
  id: uart_0
  baud_rate: 38400
  tx_pin:
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

# The base UART communication hub.
econet:
  uart: uart_0
  model: "Heatpump"

climate:
  - platform: econet
    name: ${name_base}

# Optional additional sensors.
sensor:
  - platform: econet
    hot_water:
      name: ${name_base} Hot Water
    ambient_temp:
      name: ${name_base} Ambient Temperature
    lower_water_heater_temp:
      name: ${name_base} Lower Tank Temperature
    upper_water_heater_temp:
      name: ${name_base} Upper Tank Temperature
    power_watt:
      name: ${name_base} Power
    evap_temp:
      name: ${name_base} Evaporator Temperature
    suction_temp:
      name: ${name_base} Suction Temperature
    discharge_temp:
      name: ${name_base} Discharge Temperature

binary_sensor:
  - platform: econet
    enable_state:
      name: ${name_base} Water Heater Enabled (Sensor)
    heatctrl:
      name: ${name_base} Heater Control
    fan_ctrl:
      name: ${name_base} Fan Control
    comp_rly:
      name: ${name_base} Compressor Relay

switch:
  - platform: econet
    name: ${name_base} Water Heater Enabled (Switch)
    switch_datapoint: 0    
