---
sensor:
  - platform: econet
    name: "ODU Outside Air Temperature"
    id: odu_outside_air_temperature
    sensor_datapoint: TEMP_OAT
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Evaporator Temperature"
    id: odu_evaporator_temperature
    sensor_datapoint: TEMP_EVP
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Inverter Crank Speed"
    id: odu_inverter_crank_speed
    sensor_datapoint: ISCSPEED
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Crankcase Heater Temperature"
    id: odu_crankcase_heater_temperature
    sensor_datapoint: TEMP_CPT
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Expansion Valve Current Position"
    id: odu_expansion_valve_current_position
    sensor_datapoint: EXACTUAL
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Expansion Valve Super Heat"
    id: odu_expansion_valve_super_heat
    sensor_datapoint: EXVSUPER
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Suction Line Temp"
    id: odu_suction_line_temp
    sensor_datapoint: TEMP_OST
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Saturated Suction Line Temp"
    id: odu_saturated_suction_line_temp
    sensor_datapoint: TEMP_SST
    request_mod: none
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Pressure Suction"
    id: odu_pressure_suction
    sensor_datapoint: PRES_SUC
    request_mod: none
    unit_of_measurement: "psi"
    accuracy_decimals: 1
    device_class: "pressure"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Defrost"
    id: odu_defrost
    sensor_datapoint: ODU_DEFR
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Cool Two Week Hours"
    id: odu_low_cool_two_week_hours
    sensor_datapoint: ODURCS1H
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Cool Two Week Hours"
    id: odu_high_cool_two_week_hours
    sensor_datapoint: ODURCS2H
    unit_of_measurement: ""
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Heat Two Week Hours"
    id: odu_low_heat_two_week_hours
    sensor_datapoint: ODURHS1H
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Heat Two Week Hours"
    id: odu_high_heat_two_week_hours
    sensor_datapoint: ODURHS2H
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Cool Two Week Cycles"
    id: odu_low_cool_two_week_cycles
    sensor_datapoint: ODURCS1C
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Cool Two Week Cycles"
    id: odu_high_cool_two_week_cycles
    sensor_datapoint: ODURCS2C
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Heat Two Week Cycles"
    id: odu_low_heat_two_week_cycles
    sensor_datapoint: ODURHS1C
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Heat Two Week Cycles"
    id: odu_high_heat_two_week_cycles
    sensor_datapoint: ODURHS2C
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Cool Lifetime Hours"
    id: odu_low_cool_lifetime_hours
    sensor_datapoint: ODULCS1H
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Cool Lifetime Hours"
    id: odu_high_cool_lifetime_hours
    sensor_datapoint: ODULCS2H
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Heat Lifetime Hours"
    id: odu_low_heat_lifetime_hours
    sensor_datapoint: ODULHS1H
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Heat Lifetime Hours"
    id: odu_high_heat_lifetime_hours
    sensor_datapoint: ODULHS2H
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Cool Lifetime Cycles"
    id: odu_low_cool_lifetime_cycles
    sensor_datapoint: ODULCS1C
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Cool Lifetime Cycles"
    id: odu_high_cool_lifetime_cycles
    sensor_datapoint: ODULCS2C
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Low Heat Lifetime Cycles"
    id: odu_low_heat_lifetime_cycles
    sensor_datapoint: ODULHS1C
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU High Heat Lifetime Cycles"
    id: odu_high_heat_lifetime_cycles
    sensor_datapoint: ODULHS2C
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Defrost Cycles Two Week Hours"
    id: odu_defrost_cycles_two_week_hours
    sensor_datapoint: ODURDEFC
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Defrost Cycles Lifetime Hours"
    id: odu_defrost_cycles_lifetime_hours
    sensor_datapoint: ODULDEFC
    request_mod: none
    accuracy_decimals: 1
    state_class: "total"
    entity_category: "diagnostic"
  - platform: econet
    name: "ODU Days"
    id: odu_days
    sensor_datapoint: ODU_DAYS
    request_mod: none
    accuracy_decimals: 1
    entity_category: "diagnostic"
