---
sensor:
  - platform: econet
    name: "HVAC ODU Outside Air Temperature"
    sensor_datapoint: TEMP_OAT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Evaporator Temperature"
    sensor_datapoint: TEMP_EVP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Inverter Crank Speed"
    sensor_datapoint: ISCSPEED
    unit_of_measurement: ""
    accuracy_decimals: 1
    entity_category: "diagnostic"
    icon: "mdi:speedometer"
  - platform: econet
    name: "HVAC ODU Crankcase Heater Temperature"
    sensor_datapoint: TEMP_CPT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Expansion Valve Current Position"
    sensor_datapoint: EXACTUAL
    unit_of_measurement: ""
    accuracy_decimals: 1
    entity_category: "diagnostic"
    icon: "mdi:valve"
  - platform: econet
    name: "HVAC ODU Expansion Valve Super Heat"
    sensor_datapoint: EXVSUPER
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Suction Line Temp"
    sensor_datapoint: TEMP_OST
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "HVAC ODU Pressure Suction"
    sensor_datapoint: PRES_SUC
    unit_of_measurement: "PSI"
    accuracy_decimals: 1
    device_class: "pressure"
    state_class: "measurement"
    entity_category: "diagnostic"
