---
substitutions:
  name: "econet-tlwh"
  friendly_name: "Tankless Water Heater"
  device_description: "Rheem Tankless Water Heater"
  econet_update_interval: 5s
  tankless_kbtus_per_m3: "35.300" # Natural Gas = approx 35.300, Propane = approx 88.852

packages:
  econet: !include econet_base.yaml

econet:
  dst_address: 0x1040

climate:
  - platform: econet
    id: econet_climate
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f
    current_temperature_datapoint: TEMP_OUT
    target_temperature_datapoint: WHTRSETP
    mode_datapoint: WHTRENAB
    modes:
      0: "OFF"
      1: "AUTO"

sensor:
  - platform: econet
    name: "Temperature In"
    id: temp_in
    sensor_datapoint: TEMP__IN
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Temperature Out"
    id: temp_out
    sensor_datapoint: TEMP_OUT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "BTUs Used"
    id: btus
    sensor_datapoint: WTR_BTUS
    unit_of_measurement: "kbtu"
    accuracy_decimals: 3
    entity_category: "diagnostic"
    icon: "mdi:flash"
  - platform: econet
    name: "Water Used"
    id: water_used
    sensor_datapoint: WTR_USED
    unit_of_measurement: "gal"
    accuracy_decimals: 1
    device_class: "water"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Flow Rate"
    id: flow_rate
    sensor_datapoint: FLOWRATE
    unit_of_measurement: "gpm"
    accuracy_decimals: 1
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      # Convert liters per minute to gpm
      - multiply: 0.264172
    icon: "mdi:water"
  - platform: econet
    name: "Ignition Cycles"
    id: ignition_cycles
    sensor_datapoint: IGNCYCLS
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:heating-coil"
  - platform: template
    name: "Instant BTUs"
    id: instant_btus
    unit_of_measurement: "kbtu/hr"
    accuracy_decimals: 3
    state_class: "measurement"
    entity_category: "diagnostic"
    # yamllint disable rule:line-length
    lambda: |-
      return max((id(temp_out).state - id(temp_in).state) * id(flow_rate).state * 8.334 * 60 / 0.92 / 1000, 0.0);
    # yamllint enable rule:line-length
    update_interval: ${econet_update_interval}
  - platform: template
    name: "Gas Usage"
    id: gas_usage_m3_h
    unit_of_measurement: "m³/h"
    accuracy_decimals: 3
  - platform: template
    name: "Total Gas Usage"
    id: total_gas_usage
    unit_of_measurement: "m³"
    accuracy_decimals: 5
    state_class: total_increasing
    device_class: gas

switch:
  - id: !remove alarm_beep
  - id: !remove screen_lock

interval:
  - interval: 5s
    then:
      - lambda: |-
            id(gas_usage_m3_h).publish_state(id(instant_btus).state / ${tankless_kbtus_per_m3});
            id(total_gas_usage).publish_state(id(btus).state / ${tankless_kbtus_per_m3});
