---
substitutions:
  name: "econet"
  friendly_name: "Econet Device"
  device_description: "Rheem Device"
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  github_ref: main
  external_components_source: github://esphome-econet/esphome-econet@${github_ref}
  logger_level: WARN
  econet_update_interval: 30s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: "2023.2.0"
  platform: $platform
  board: $board
  project:
    name: "esphome-econet.esphome-econet"
    version: 1.1.0

preferences:
  flash_write_interval: "24h"

wifi:
  ap:

captive_portal:

api:

ota:

logger:
  baud_rate: 0  # Make sure logging is not using the serial port
  level: ${logger_level}
  tx_buffer_size: 2000

external_components:
  - source: ${external_components_source}

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

econet:
  uart_id: uart_0
  update_interval: ${econet_update_interval}

sensor:
  - platform: econet
    name: "Active Alerts"
    sensor_datapoint: ALRMALRT
    request_mod: 1
    accuracy_decimals: 0
    icon: "mdi:alert"
    state_class: "measurement"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    entity_category: "diagnostic"

text_sensor:
  - platform: econet
    name: "Alarm 1"
    sensor_datapoint: ALARM_01
    request_mod: 1
    icon: "mdi:alert"
    entity_category: "diagnostic"
  - platform: econet
    name: "Alarm 2"
    sensor_datapoint: ALARM_02
    request_mod: 1
    icon: "mdi:alert"
    entity_category: "diagnostic"
  - platform: econet
    name: "Alarm 3"
    sensor_datapoint: ALARM_03
    request_mod: 1
    icon: "mdi:alert"
    entity_category: "diagnostic"
  - platform: econet
    name: "Alarm 4"
    sensor_datapoint: ALARM_04
    request_mod: 1
    icon: "mdi:alert"
    entity_category: "diagnostic"
  - platform: econet
    name: "Software Version Number"
    sensor_datapoint: SW_VERSN
    request_mod: 2
    request_once: true
    icon: "mdi:information-box"
    entity_category: "diagnostic"

switch:
  - platform: econet
    name: "Beep On Alarm"
    switch_datapoint: ALRMBEEP
    request_mod: 2
    icon: "mdi:alarm-note"
    entity_category: "config"
  - platform: econet
    name: "Screen Adjustment Lock"
    switch_datapoint: SCRNLOCK
    request_mod: 2
    icon: "mdi:gesture-tap-button"
    entity_category: "config"
  - platform: econet
    name: "Screen Unit in °C"
    switch_datapoint: DISPUNIT
    request_mod: 2
    icon: "mdi:temperature-celsius"
    entity_category: "config"
  - platform: econet
    id: resetdev
    switch_datapoint: RESETDEV
    request_mod: none
    internal: true
  - platform: econet
    id: alreset
    switch_datapoint: ALRESET
    request_mod: none
    internal: true

button:
  - platform: restart
    name: "Restart ESP"
    icon: "mdi:restart"
    entity_category: "config"
  - platform: template
    name: "Restart Microcontroller"
    icon: "mdi:restart"
    entity_category: "config"
    on_press:
      - switch.turn_on: resetdev
      - delay: 1s
      - switch.turn_off: resetdev
  - platform: template
    name: "Alarm Reset"
    icon: "mdi:restart-alert"
    entity_category: "config"
    on_press:
      - switch.turn_on: alreset
      - delay: 1s
      - switch.turn_off: alreset
