---
substitutions:
  name: "econet-hvac"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"
  thermostat_address: "0x380"
  wifi_module_address: "0x340"

packages:
  econet: !include econet_base.yaml

econet:
  dst_address: ${thermostat_address}

climate:
  - platform: econet
    id: econet_climate
    src_address: ${thermostat_address}
    name: "HVAC"
    visual:
      min_temperature: "50 째F"
      max_temperature: "90 째F"
      temperature_step:
        target_temperature: "0.5 째F"
        current_temperature: "0.1 째F"
      min_humidity: 10
      max_humidity: 80
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STAT_FAN
    custom_fan_mode_no_schedule_datapoint: STATNFAN
    follow_schedule_datapoint: SCHEDULE
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"
    current_humidity_datapoint: RELH7005
    target_dehumidification_level_datapoint: DHUMSETP

sensor:
  - platform: econet
    name: "Airhandler CFM"
    id: airhandler_cfm
    icon: "mdi:fan"
    sensor_datapoint: F_ACTCFM
    unit_of_measurement: "cfm"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 9.9
  - platform: econet
    name: "Airhandler RPM"
    icon: "mdi:fan"
    id: airhandler_rpm
    sensor_datapoint: F_ACTRPM
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 9.9
  - platform: econet
    name: "Static Pressure"
    id: static_pressure
    icon: "mdi:air-filter"
    sensor_datapoint: STATIC_P
    accuracy_decimals: 6
    unit_of_measurement: "in"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 0.02
  - platform: econet
    name: "Thermostat Current Humidity"
    id: thermostat_current_humidity
    sensor_datapoint: RELH7005
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: "humidity"
    state_class: "measurement"

text_sensor:
  - platform: econet
    name: "Operating Mode"
    id: operating_mode
    icon: "mdi:hvac"
    sensor_datapoint: HVACMODE
  - platform: econet
    name: "Auto Mode"
    id: auto_mode
    icon: "mdi:hvac"
    sensor_datapoint: AUTOMODE
  - id: !extend sw_version
    name: "Thermostat SW Version"
    src_address: ${thermostat_address}
  - platform: econet
    name: "WiFi SW Version"
    id: wifi_sw_version
    sensor_datapoint: SW_VERSN
    src_address: ${wifi_module_address}
    request_mod: none
    icon: "mdi:information-box"
    entity_category: "diagnostic"

select:
  - platform: "econet"
    name: "Fan Duty Cycle"
    id: fan_duty
    enum_datapoint: FAN_MODE
    options:
      0: "Continuous"
      1: "Timed, 10 min"
      2: "Timed, 20 min"
      3: "Timed, 30 min"
      4: "Timed, 40 min"
    icon: "mdi:fan"
    request_mod: 9

switch:
  - platform: econet
    name: "Dehumidification Enable State"
    id: dehumidification_enable_state
    switch_datapoint: DHUMENAB
    icon: "mdi:air-humidifier-off"
  - platform: econet
    name: "Follow Schedule"
    id: schedule
    switch_datapoint: SCHEDULE
