---
substitutions:
  primary_thermostat_address: "0x380"
  wifi_module_address: "0x340"

# packages:
#   econet: !include econet_hvac_furnace.yaml

text_sensor:
  - platform: econet
    name: HVAC Zone ${zonenumber} Name
    src_address: ${zone_thermostat_address}
    sensor_datapoint: EQP_NAME
    request_mod: ${zone_thermostat_requestmod}
    request_once: true

climate:
  - platform: econet
    id: econet_climate_zone${zonenumber}
    name: HVAC ${zonename} Climate
    src_address: ${zone_thermostat_address}
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STATNFAN
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"
    current_humidity_datapoint: RELH7005
    target_dehumidification_level_datapoint: DHUMSETP


sensor:
  - platform: econet
    src_address: ${primary_thermostat_address}
    name: HVAC ${zonename} CFM
    sensor_datapoint: Z${zonenumber}CFMDSP
    request_mod: ${primary_thermostat_requestmod}
    state_class: "measurement"
    entity_category: "diagnostic"
    unit_of_measurement: "cfm"

binary_sensor:
  - platform: econet
    src_address: ${primary_thermostat_address}
    name: HVAC Zone ${zonenumber} enabled
    sensor_datapoint: ZON${zonenumber}ENAB
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
#    disabled_by_default: true
    request_mod: ${primary_thermostat_requestmod}
    request_once: true
