---
substitutions:
  name: "econet-hvac_furnace"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"

packages:
  econet: !include econet_hvac.yaml

sensor:
  - platform: econet
    name: "Register Air Temperature"
    id: register_air_temperature
    sensor_datapoint: FURNSTMP
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Return Air Temperature"
    id: return_air_temperature
    sensor_datapoint: FURNRTMP
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
