---
substitutions:
  name: "econet-hpwh"
  friendly_name: "Water Heater"
  device_description: "Rheem Heat Pump Water Heater"
  sensor_power_filters_lambda: return x;

packages:
  econet: !include econet_base.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_heatpump_water_heater.yaml@${github_ref}
  import_full_config: false

econet:
  model: "Heatpump"

climate:
  - platform: econet
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f

sensor:
  - platform: econet
    name: "Hot Water"
    sensor_datapoint: HOTWATER
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: "moisture"
    state_class: "measurement"
  - platform: econet
    name: "Ambient Temperature"
    sensor_datapoint: AMBIENTT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Lower Tank Temperature"
    sensor_datapoint: LOHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Upper Tank Temperature"
    sensor_datapoint: UPHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Power"
    sensor_datapoint: POWRWATT
    unit_of_measurement: "W"
    accuracy_decimals: 3
    device_class: "power"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - lambda: ${sensor_power_filters_lambda}
  - platform: econet
    name: "Evaporator Temperature"
    sensor_datapoint: EVAPTEMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Suction Temperature"
    sensor_datapoint: SUCTIONT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Discharge Temperature"
    sensor_datapoint: DISCTEMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"

binary_sensor:
  - platform: econet
    name: "Compressor"
    sensor_datapoint: COMP_RLY
    device_class: "running"

text_sensor:
  - platform: econet
    name: "Fan Speed"
    sensor_datapoint: FAN_CTRL
    icon: "mdi:fan"
  - platform: econet
    name: "Heating Element State"
    sensor_datapoint: HEATCTRL
    icon: "mdi:heating-coil"
  - platform: econet
    name: "Model Number"
    sensor_datapoint: PRODMODN
    request_mod: 2
    request_once: true
    icon: "mdi:information-box"
    entity_category: "diagnostic"
  - platform: econet
    name: "Serial Number"
    sensor_datapoint: PRODSERN
    request_mod: 2
    request_once: true
    icon: "mdi:information-box"
    entity_category: "diagnostic"
  - platform: econet
    name: "Software Version Number"
    sensor_datapoint: SW_VERSN
    request_mod: 2
    request_once: true
    icon: "mdi:information-box"
    entity_category: "diagnostic"
