---
substitutions:
  name: "econet-hvac"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"

packages:
  econet: !include econet_base.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_hvac.yaml@${github_ref}
  import_full_config: false

econet:
  dst_address: 0x380
  on_datapoint_update:
    - sensor_datapoint: AIRHSTAT
      datapoint_type: raw
      then:
        # yamllint disable rule:line-length
        - lambda: |-
            ESP_LOGD("main", "on_datapoint_update %s", format_hex_pretty(x).c_str());
            id(blower_cfm).publish_state((x[16] << 8) + x[17]);
            id(blower_rpm).publish_state((x[20] << 8) + x[21]);
        # yamllint enable rule:line-length

climate:
  - platform: econet
    name: "HVAC"
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT_STAT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STATNFAN
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"

sensor:
  - platform: econet
    name: "HVAC Operating Mode"
    sensor_datapoint: HVACMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
    icon: "mdi:hvac"
  - platform: econet
    name: "HVAC Thermostat Temperature"
    sensor_datapoint: SPT_STAT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Cooling Setpoint"
    sensor_datapoint: COOLSETP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
  - platform: econet
    name: "HVAC Auto Mode"
    sensor_datapoint: AUTOMODE
    unit_of_measurement: ""
    accuracy_decimals: 0
    icon: "mdi:hvac"
  - platform: econet
    name: "Thermostat Current Humidity"
    sensor_datapoint: RELH7005
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: "humidity"
    state_class: "measurement"
  - platform: template
    name: "HVAC Air Handler CFM"
    id: blower_cfm
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:fan"
  - platform: template
    name: "HVAC Air Handler RPM"
    id: blower_rpm
    unit_of_measurement: ""
    accuracy_decimals: 0
    entity_category: "diagnostic"
    icon: "mdi:fan"

text_sensor:
  - platform: econet
    name: "HVAC Operating Mode Text"
    sensor_datapoint: HVACMODE
    icon: "mdi:hvac"
  - platform: econet
    name: "HVAC Auto Mode Text"
    sensor_datapoint: AUTOMODE
    icon: "mdi:hvac"

number:
  - platform: econet
    name: "HVAC Dehumidification Setting Control"
    number_datapoint: DHUMSETP
    min_value: 10
    max_value: 80
    step: 1
    mode: "slider"
    icon: "mdi:air-humidifier-off"

switch:
  - platform: econet
    name: "HVAC Dehumidification Enable State"
    switch_datapoint: DHUMENAB
    icon: "mdi:air-humidifier-off"
