---
substitutions:
  external_components_source: components  # Build with local code instead of pulling from Github

# This removes the non-zone climate entity for zone1, to be replaced below.
climate:
  - id: !remove econet_climate

econet:
  request_mod_addresses:
    10: 0x380
    11: 0x680
    12: 0x681

packages:
  # Uncomment any zones as appropriate for your system.
  zone1: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "1"
      zonename: "Zone1"
      zone_thermostat_requestmod: 10
      primary_thermostat_requestmod: 6
      zone_thermostat_address: 0x380


  zone2: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "2"
      zonename: "Zone2"
      zone_thermostat_requestmod: 11
      primary_thermostat_requestmod: 6
      zone_thermostat_address: 0x680

  zone3: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "3"
      zonename: "Zone3"
      zone_thermostat_requestmod: 12
      primary_thermostat_requestmod: 6
      zone_thermostat_address: 0x681

  # Comment out the bypass section if your system has a mechanical (non-electrical) for the bypass zone
  bypasszone: !include
    file: econet_hvac_zone_bypass.yaml
    vars:
      zonenumber: "6"
      zonename: "Zone6"
      zone_thermostat_requestmod: 15
      primary_thermostat_requestmod: 6

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
