---
substitutions:
  name: "econet-hvac_furnace"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"
  furnace_address: "448"
  furnace_kbtus_per_m3: "35.300"  # Natural Gas = approx 35.300, Propane = approx 88.852

packages:
  econet: !include econet_hvac.yaml

econet:
  request_mod_addresses:
    5: ${furnace_address}
    6: ${furnace_address}
  on_datapoint_update:
    - sensor_datapoint: HWSTATUS
      datapoint_type: raw
      src_address: ${furnace_address}
      then:
        - lambda: |-
            if (x.size() <= 138) {
              return;
            }
            id(airhandler_cfm).publish_state((x[13] << 8) + x[14]);
            id(airhandler_rpm).publish_state((x[17] << 8) + x[18]);
            id(heat_capacity).publish_state(x[11]);
            id(compressor_stage).publish_state(x[12]);
            id(heat_stage).publish_state(x[26]);
            id(static_pressure).publish_state(((x[15] << 8) + x[16]) / 5280.0);
            id(return_air_temperature).publish_state(((x[50] << 8) + x[51]) / 10.0);
            id(outdoor_air_temperature).publish_state(((x[52] << 8) + x[53])/10.0);
            id(flame_sensor).publish_state(x[33] / 10.0);
            // Accumulators
            id(low_heat_2week_cycles).publish_state((x[102] << 8) + x[103]);
            id(high_heat_2week_cycles).publish_state((x[104] << 8) + x[105]);
            id(blower_2week_cycles).publish_state((x[106] << 8) + x[107]);
            id(powered_2week_cycles).publish_state((x[108] << 8) + x[109]);
            id(low_heat_2week_hrs).publish_state((x[122] << 8) + x[123]);
            id(high_heat_2week_hrs).publish_state((x[124] << 8) + x[125]);
            id(blower_2week_hrs).publish_state((x[126] << 8) + x[127]);
            id(low_heat_lifetime_cycles).publish_state((x[111] << 8) + x[112]);
            id(high_heat_lifetime_cycles).publish_state((x[114] << 8) + x[115]);
            id(blower_lifetime_cycles).publish_state((x[117] << 8) + x[118]);
            id(powered_lifetime_cycles).publish_state((x[120] << 8) + x[121]);
            id(low_heat_lifetime_hrs).publish_state((x[129] << 8) + x[130]);
            id(high_heat_lifetime_hrs).publish_state((x[132] << 8) + x[133]);
            id(blower_lifetime_hrs).publish_state((x[135] << 8) + x[136]);
            id(powered_lifetime_days).publish_state((x[137] << 8) + x[138]);
            id(supply_air_temperature).publish_state(((x[145] << 8) + x[146])/10.0);
    - sensor_datapoint: HRHEEMID
      request_mod: 5
      request_once: true
      src_address: ${furnace_address}
      datapoint_type: raw
      then:
        - lambda: |-
            if (x.size() <= 52) {
              return;
            }
            std::string str(x.begin(), x.end());
            std::string model = str.substr(4, 24);
            model.erase(remove(model.begin(), model.end(), '\00'), model.end());
            id(hw_model_num).publish_state(model);
            std::string serial = str.substr(28, 24);
            serial.erase(remove(serial.begin(), serial.end(), '\00'), serial.end());
            id(hw_serial_num).publish_state(serial);
    - sensor_datapoint: HWELL_ID
      request_mod: 6
      request_once: true
      src_address: ${furnace_address}
      datapoint_type: raw
      then:
        - lambda: |-
            if (x.size() <= 52) {
              return;
            }
            std::string str(x.begin(), x.end());
            std::string sw1 = str.substr(4, 24);
            sw1.erase(remove(sw1.begin(), sw1.end(), '\00'), sw1.end());
            id(furnace_sw).publish_state(sw1);
            std::string sw2 = str.substr(28, 24);
            sw2.erase(remove(sw2.begin(), sw2.end(), '\00'), sw2.end());
            id(furnace_sw2).publish_state(sw2);

sensor:
  - platform: econet
    name: "Supply Air Temperature"
    id: supply_air_temperature
    sensor_datapoint: FURNSTMP
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    disabled_by_default: true
    request_mod: none
    filters:
      - delta: 0.9
  - platform: econet
    name: "Return Air Temperature"
    id: return_air_temperature
    sensor_datapoint: FURNRTMP
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    request_mod: none
    filters:
      - delta: 0.9
  - platform: template
    name: "Outdoor Air Temperature"
    id: outdoor_air_temperature
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    disabled_by_default: true
    filters:
      - delta: 0.9
  - platform: template
    name: "Flame Sensor"
    id: flame_sensor
    device_class: "current"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 4
    unit_of_measurement: "mA"
    filters:
      - delta: 0.09
      - multiply: .001  # Convert from uA to mA
  - platform: econet
    name: "Furnace AFUE"
    id: furnace_afue
    sensor_datapoint: FURNAFUE
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: "mdi:fire-circle"
    request_once: true
    filters:
      - lambda: |-  # Some furnaces seem to report waste rather than efficiency; this normalizes things to traditional AFUE
          if (x < 50) return 100-x;
          return x;
  - platform: econet
    name: "Furnace High Heat BTU Output"
    id: furnace_hh_btus
    sensor_datapoint: FURNHBTU
    entity_category: "diagnostic"
    unit_of_measurement: "btu/h"
    icon: "mdi:gas-burner"
    request_once: true
  - platform: econet
    name: "Furnace Low Heat BTU Output"
    id: furnace_lh_btus
    sensor_datapoint: FURNLBTU
    entity_category: "diagnostic"
    unit_of_measurement: "btu/h"
    icon: "mdi:gas-burner"
    request_once: true
  - platform: template
    name: "Two Week Cycles - Low Heat"
    id: low_heat_2week_cycles
    icon: "mdi:sync"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Cycles - High Heat"
    id: high_heat_2week_cycles
    icon: "mdi:sync"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Cycles - Blower"
    id: blower_2week_cycles
    icon: "mdi:sync"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Cycles - Powered"
    id: powered_2week_cycles
    icon: "mdi:sync"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Hours - Low Heat"
    unit_of_measurement: "h"
    id: low_heat_2week_hrs
    icon: "mdi:timelapse"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Hours - High Heat"
    unit_of_measurement: "h"
    id: high_heat_2week_hrs
    icon: "mdi:timelapse"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Two Week Hours - Blower"
    unit_of_measurement: "h"
    id: blower_2week_hrs
    icon: "mdi:timelapse"
    state_class: "measurement"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Cycles - Low Heat"
    id: low_heat_lifetime_cycles
    icon: "mdi:sync"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Cycles - High Heat"
    id: high_heat_lifetime_cycles
    icon: "mdi:sync"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Cycles - Blower"
    id: blower_lifetime_cycles
    icon: "mdi:sync"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Cycles - Powered"
    id: powered_lifetime_cycles
    icon: "mdi:sync"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Hours - Low Heat"
    unit_of_measurement: "h"
    id: low_heat_lifetime_hrs
    icon: "mdi:timelapse"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Hours - High Heat"
    unit_of_measurement: "h"
    id: high_heat_lifetime_hrs
    icon: "mdi:timelapse"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Hours - Blower"
    unit_of_measurement: "h"
    id: blower_lifetime_hrs
    icon: "mdi:timelapse"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Lifetime Days - Powered"
    unit_of_measurement: "d"
    id: powered_lifetime_days
    icon: "mdi:timelapse"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    accuracy_decimals: 0
    filters:
      - delta: 0.9
  - platform: template
    name: "Instant BTU Output"
    id: instant_btu_output
    unit_of_measurement: "kbtu/h"
    icon: "mdi:gas-burner"
    state_class: "measurement"
    accuracy_decimals: 3
    filters:
      - delta: 0.9
  - platform: template
    name: "Instant BTU Usage"
    id: instant_btu_usage
    unit_of_measurement: "kbtu/h"
    icon: "mdi:gas-burner"
    state_class: "measurement"
    accuracy_decimals: 3
    filters:
      - delta: 0.9
  - platform: template
    name: "Instant Gas Usage"
    id: gas_usage_m3_h
    unit_of_measurement: "m³/h"
    icon: "mdi:meter-gas"
    state_class: "measurement"
    accuracy_decimals: 3
  - platform: integration
    name: "Total Daily Gas"
    sensor: gas_usage_m3_h
    time_unit: h
    state_class: total_increasing
    device_class: gas
    accuracy_decimals: 5
    unit_of_measurement: "m³"
  - platform: econet
    name: "Indoor KW"
    id: indoor_kw
    sensor_datapoint: INDOORKW
    entity_category: "diagnostic"
    state_class: "total_increasing"
    device_class: energy
    unit_of_measurement: "kWh"
  - platform: template
    name: "Heating Capacity"
    id: heat_capacity
    entity_category: "diagnostic"
    accuracy_decimals: 0
    state_class: "measurement"
    icon: "mdi:gas-burner"
    filters:
      - delta: 0.9
  - platform: template
    name: "Heating Stage"
    id: heat_stage
    entity_category: "diagnostic"
    accuracy_decimals: 0
    state_class: "measurement"
    icon: "mdi:gas-burner"
    filters:
      - delta: 0.9
  - platform: template
    name: "Compressor Stage"
    id: compressor_stage
    entity_category: "diagnostic"
    accuracy_decimals: 0
    state_class: "measurement"
    icon: "mdi:sun-snowflake-variant"
    filters:
      - delta: 0.9

text_sensor:
  - platform: template
    name: "Furnace Model Number"
    id: hw_model_num
    icon: "mdi:information-box"
    entity_category: "diagnostic"
  - platform: template
    name: "Furnace Serial Number"
    id: hw_serial_num
    icon: "mdi:information-box"
    entity_category: "diagnostic"
  - platform: template
    name: "Furnace SW Version"
    id: furnace_sw
    icon: "mdi:information-box"
    entity_category: "diagnostic"
  - platform: template
    name: "Furnace SW Version 2"
    id: furnace_sw2
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    disabled_by_default: true

interval:
  - interval: 5s
    then:
      - lambda: |-
          float furnace_kbtus = id(furnace_hh_btus).state / 1000.0 * id(heat_capacity).state / 100.0;
          float furnace_eff = id(furnace_afue).state / 100.0;
          id(instant_btu_output).publish_state(furnace_kbtus);
          id(instant_btu_usage).publish_state(furnace_kbtus / furnace_eff);
          id(gas_usage_m3_h).publish_state(furnace_kbtus / furnace_eff / ${furnace_kbtus_per_m3});
