---
substitutions:
  name: "econet-hvac"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"

packages:
  econet: !include econet_base.yaml

econet:
  dst_address: 0x380

climate:
  - platform: econet
    id: econet_climate
    name: "HVAC"
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT_STAT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STAT_FAN
    custom_fan_mode_no_schedule_datapoint: STATNFAN
    follow_schedule_datapoint: SCHEDULE
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"

sensor:
  - platform: econet
    name: "Airhandler CFM"
    id: airhandler_cfm
    sensor_datapoint: F_ACTCFM
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 9.9
  - platform: econet
    name: "Airhandler RPM"
    id: airhandler_rpm
    sensor_datapoint: F_ACTRPM
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 9.9
  - platform: econet
    name: "Static Pressure"
    id: static_pressure
    sensor_datapoint: STATIC_P
    accuracy_decimals: 6
    unit_of_measurement: "in"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 0.02
  - platform: econet
    name: "Thermostat Current Humidity"
    id: thermostat_current_humidity
    sensor_datapoint: RELH7005
    unit_of_measurement: "%"
    accuracy_decimals: 1
    device_class: "humidity"
    state_class: "measurement"

text_sensor:
  - platform: econet
    name: "Operating Mode"
    id: operating_mode
    sensor_datapoint: HVACMODE
  - platform: econet
    name: "Auto Mode"
    id: auto_mode
    sensor_datapoint: AUTOMODE

number:
  - platform: econet
    name: "Dehumidification Setting Control"
    id: dehumidification_setting_control
    number_datapoint: DHUMSETP
    min_value: 10
    max_value: 80
    step: 1
    mode: "slider"
    icon: "mdi:air-humidifier-off"

switch:
  - platform: econet
    name: "Dehumidification Enable State"
    id: dehumidification_enable_state
    switch_datapoint: DHUMENAB
    icon: "mdi:air-humidifier-off"
  - platform: econet
    name: "Follow Schedule"
    id: schedule
    switch_datapoint: SCHEDULE
