---
substitutions:
  name: "econet-etwh"
  friendly_name: "Water Heater"
  device_description: "Rheem Electric Tank Water Heater"
  sensor_power_filters_lambda: return x;

packages:
  econet: !include econet_base.yaml

econet:
  dst_address: 0x1200

climate:
  - platform: econet
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f
    current_temperature_datapoint: UPHTRTMP
    target_temperature_datapoint: WHTRSETP
    mode_datapoint: WHTRENAB
    modes:
      0: "OFF"
      1: "AUTO"
    custom_preset_datapoint: WHTRCNFG
    custom_presets:
      0: "Energy Saver"
      1: "Performance"

sensor:
  - platform: econet
    name: "Lower Tank Temperature"
    id: lower_tank_temp
    sensor_datapoint: LOHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Upper Tank Temperature"
    id: upper_tank_temp
    sensor_datapoint: UPHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Power"
    id: power
    sensor_datapoint: POWRWATT
    unit_of_measurement: "W"
    accuracy_decimals: 3
    device_class: "power"
    state_class: "measurement"
    filters:
      - lambda: ${sensor_power_filters_lambda}

text_sensor:
  - platform: econet
    name: "Heating Element State"
    id: heating_element
    sensor_datapoint: HEATCTRL
    icon: "mdi:heating-coil"
  - platform: econet
    name: "Mode"
    id: mode
    sensor_datapoint: WHTRMODE
    entity_category: "diagnostic"
