---
substitutions:
  name: "econet-hpwh"
  friendly_name: "Water Heater"
  device_description: "Rheem Heat Pump Water Heater"
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev
  external_components_source: github://esphome-econet/esphome-econet@main
  logger_level: WARN
  econet_update_interval: 30s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: "2023.2.0"
  platform: $platform
  board: $board
  project:
    name: "esphome-econet.esphome-econet"
    version: 0.2.4

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/econet_heatpump_water_heater.yaml@main
  import_full_config: false

preferences:
  flash_write_interval: "24h"

wifi:
  ap:

captive_portal:

api:

ota:

logger:
  baud_rate: 0  # Make sure logging is not using the serial port
  level: ${logger_level}
  tx_buffer_size: 2000

external_components:
  - source: ${external_components_source}

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

econet:
  uart_id: uart_0
  model: "Heatpump"
  update_interval: ${econet_update_interval}

climate:
  - platform: econet
    name: None
    visual:
      min_temperature: "43.3333"
      max_temperature: "60"
      temperature_step: 1.0f

sensor:
  - platform: econet
    name: "Hot Water"
    sensor_datapoint: HOTWATER
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: "moisture"
    state_class: "measurement"
  - platform: econet
    name: "Ambient Temperature"
    sensor_datapoint: AMBIENTT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Lower Tank Temperature"
    sensor_datapoint: LOHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Upper Tank Temperature"
    sensor_datapoint: UPHTRTMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Power"
    sensor_datapoint: POWRWATT
    unit_of_measurement: "W"
    accuracy_decimals: 3
    device_class: "power"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Evaporator Temperature"
    sensor_datapoint: EVAPTEMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Suction Temperature"
    sensor_datapoint: SUCTIONT
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: econet
    name: "Discharge Temperature"
    sensor_datapoint: DISCTEMP
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"
    entity_category: "diagnostic"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    entity_category: "diagnostic"

binary_sensor:
  - platform: econet
    name: "Compressor Relay"
    sensor_datapoint: COMP_RLY
    device_class: "running"

text_sensor:
  - platform: econet
    name: "Fan Speed"
    sensor_datapoint: FAN_CTRL
    icon: "mdi:fan"
  - platform: econet
    name: "Heating Element State"
    sensor_datapoint: HEATCTRL
    icon: "mdi:heating-coil"
