---
substitutions:
  name: "econet-hvac_air_handler"
  friendly_name: "Rheem HVAC"
  device_description: "Rheem HVAC"

packages:
  econet: !include econet_hvac.yaml

sensor:
  - platform: econet
    name: "Supply Air Temperature"
    id: supply_air_temperature
    sensor_datapoint: TEMP_LAT
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 0.9
  - platform: econet
    name: "Return Air Temperature"
    id: return_air_temperature
    sensor_datapoint: TEMP_RAT
    device_class: "temperature"
    unit_of_measurement: "°F"
    state_class: "measurement"
    entity_category: "diagnostic"
    filters:
      - delta: 0.9

binary_sensor:
  - platform: econet
    name: "Electric Heat Relay 1"
    id: electric_heat_relay_1
    sensor_datapoint: HT1_RELY
    device_class: "heat"
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
    disabled_by_default: true
  - platform: econet
    name: "Electric Heat Relay 2"
    id: electric_heat_relay_2
    sensor_datapoint: HT2_RELY
    device_class: "heat"
    icon: "mdi:heating-coil"
    entity_category: "diagnostic"
    disabled_by_default: true
