---
substitutions:
  external_components_source: components  # Build with local code instead of pulling from Github

# This removes the non-zone climate entity for zone1, to be replaced below.
climate:
  - id: !remove econet_climate

packages:
  # Uncomment any zones as appropriate for your system.
  zone1: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "1"
      zonename: "Zone1"
      requestmod: 10
      zone_thermostat_address: 0x380

  zone2: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "2"
      zonename: "Zone2"
      requestmod: 11
      zone_thermostat_address: 0x680

  zone3: !include
    file: econet_hvac_zone_template.yaml
    vars:
      zonenumber: "3"
      zonename: "Zone3"
      requestmod: 12
      zone_thermostat_address: 0x681

  # Comment out the bypass section if your system has a mechanical (non-electrical) for the bypass zone
  bypasszone: !include
    file: econet_hvac_zone_bypass.yaml
    vars:
      zonenumber: "6"
      zonename: "Zone6"
      requestmod: 15

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
