---
substitutions:
  tx_pin: GPIO19
  rx_pin: GPIO22
  platform: esp32
  board: esp32dev

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    # Change this file to the correct one for your device
    file: econet_heatpump_water_heater.yaml
    # file: econet_hvac.yaml
    # Use this if you have a comminicating outdoor unit (ODU)
    # files: [econet_hvac.yaml, econet_hvac_odu.yaml]
    # file: econet_tankless_water_heater.yaml
    # file: econet_electric_tank_water_heater.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# If you have an RS485-TTL module with flow control pin, such as MAX485,
# wire DE and RE to GPIO0 and uncomment the following 2 lines:
# econet:
#   flow_control_pin: GPIO0

# If you don't want to expose specific sensors to Home Assistant:
# text_sensor:
#   - id: !extend sw_version
#     internal: true
