---
substitutions:
  external_components_source: components  # Build with local code instead of pulling from Github

packages:  # Change this file to the correct one(s) for your device
  econet-hpwh: !include econet_heatpump_water_heater.yaml
  # econet-hvac: !include econet_hvac.yaml
  # econet-hvac-odu: !include econet_hvac_odu.yaml  # Must be included with econet_hvac.yaml
  # econet-tlwh: !include econet_tankless_water_heater.yaml
  # econet-etwh: !include econet_electric_tank_water_heater.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
