---
substitutions:
  external_components_source: components  # Build with local code instead of pulling from Github

packages:  # Change this file to the correct one(s) for your device
  econet-hpwh: !include econet_heatpump_water_heater.yaml
  # econet-hvac-furnace: !include econet_hvac_furnace.yaml
  # econet-hvac-air-handler: !include econet_hvac_air_handler.yaml
  # econet-hvac-odu: !include econet_hvac_odu.yaml  # Depends on econet_hvac_[furnace or air_handler].yaml
  # econet-tlwh: !include econet_tankless_water_heater.yaml
  # econet-etwh: !include econet_electric_tank_water_heater.yaml
  # for hvac zones, uncomment lines below as appropriate.  requires an econet-hvac-furnace or econet-hvac-air-handler
  # econet-zone1: !include {file: econet_hvac_zone1.yaml, vars: {zonename: "Zone1Name"}} # zonename is required.
  # econet-zone2: !include {file: econet_hvac_zone2.yaml, vars: {zonename: "Zone2Name"}} # zonename is required
  # econet-zone3: !include {file: econet_hvac_zone3.yaml, vars: {zonename: "Zone3Name"}} # zonename is required
  # econet-zone3-bypass: !include econet_hvac_zone3_electronicbypass.yaml
  # zones 4, 5, 6 not yet supported.  only zone6 as bypass is supported.  if you have these zones, please file an issue
  # econet-zone6-bypass: !include econet_hvac_zone6_electronicbypass.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# If you have UNSUPPORTED sensors add something like the following to disable them
# sensor:
#   - id: !extend hot_water
#     request_mod: none
#     internal: true
