---
substitutions:
  primary_thermostat_address: "0x380"

text_sensor:
  - platform: econet
    id: zone${zonenumber}_equipment_name
    name: Zone${zonenumber} Equipment Name
    src_address: ${zone_thermostat_address}
    sensor_datapoint: EQP_NAME
    request_mod: ${zone_thermostat_requestmod}
    entity_category: "diagnostic"
    request_once: true

climate:
  - platform: econet
    id: zone${zonenumber}_climate
    name: ${zonename} Climate
    request_mod: ${zone_thermostat_requestmod}
    src_address: ${zone_thermostat_address}
    visual:
      min_temperature: "10"
      max_temperature: "32.2222"
      temperature_step: 1.0f
    current_temperature_datapoint: SPT
    target_temperature_low_datapoint: HEATSETP
    target_temperature_high_datapoint: COOLSETP
    mode_datapoint: STATMODE
    modes:
      0: "HEAT"
      1: "COOL"
      2: "HEAT_COOL"
      3: "FAN_ONLY"
      4: "OFF"
    custom_fan_mode_datapoint: STAT_FAN
    custom_fan_mode_no_schedule_datapoint: STATNFAN
    follow_schedule_datapoint: SCHEDULE
    custom_fan_modes:
      0: "Automatic"
      1: "Speed 1 (Low)"
      2: "Speed 2 (Medium Low)"
      3: "Speed 3 (Medium)"
      4: "Speed 4 (Medium High)"
      5: "Speed 5 (High)"
    current_humidity_datapoint: RELH7005
    target_dehumidification_level_datapoint: DHUMSETP

<<: !include econet_hvac_zone_sensors_template.yaml
