---
substitutions:
  tx_pin: GPIO16
  rx_pin: GPIO17
  platform: esp32
  board: m5stack-core-esp32


packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_hvac_furnace.yaml
  # Uncomment if you have an communicationg Outdoor Unit
  # econet-hvac-odu:
  #   url: https://github.com/esphome-econet/esphome-econet
  #   ref: main
  #   file: econet_hvac_odu.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${platform}.yaml@${github_ref}
  import_full_config: false

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5
  
# Remove all things related to Wifi as the PoESP32 series does not support it
 wifi: !remove
 ap: !remove
 captive_portal: !remove
 improv_serial: !remove

 platform: !remove wifi_signal
