---
substitutions:
  tx_pin: GPIO6
  rx_pin: GPIO5

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_hvac_air_handler.yaml
  # Uncomment if you have an communicating Outdoor Unit
  # econet-hvac-odu:
  #   url: https://github.com/esphome-econet/esphome-econet
  #   ref: main
  #   file: econet_hvac_odu.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-esp32s3.yaml@${github_ref}
  import_full_config: false

# Uncomment the below to use Wi-Fi settings from your secrets.yaml file
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
