---
substitutions:
  tx_pin: GPIO4
  rx_pin: GPIO5
  platform: esp8266
  board: d1_mini

packages:
  econet-etwh: !include ../econet_electric_tank_water_heater.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${platform}.yaml@${github_ref}
  import_full_config: false
