---
substitutions:
  tx_pin: GPIO6
  rx_pin: GPIO5
  board: esp32-s3-devkitc-1
  platform: esp32s3

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_hvac_furnace.yaml
  # Uncomment if you have an communicationg Outdoor Unit
  # econet-hvac-odu:
  #   url: https://github.com/esphome-econet/esphome-econet
  #   ref: main
  #   file: econet_hvac_odu.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${platform}.yaml@${github_ref}
  import_full_config: false

esphome:
  platform: !remove
  board: !remove

esp32:
  board: ${board}
  variant: esp32s3

# Uncomment the below to use Wi-Fi settings from your secrets.yaml file
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
